# SPDX-FileCopyrightText: 2026 Mercury Technologies, Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

filegroup(
    name = "nix_overlays",
    srcs = glob([
        "**/flake.lock",
        "**/*.nix",
        "**/*.sh",
        "**/*.patch",
        "packages/buck2-source/Cargo.lock",
        "packages/buck2-source/Cargo.lock.next",
        "packages/buck2-source/versions.json",
        "packages/buck2-change-detector/Cargo.lock",
    ]),
    visibility = ["PUBLIC"],
)
