# SPDX-FileCopyrightText: 2026 Mercury Technologies, Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

constraint(
    name = "link_style",
    default = "auto",
    values = [
        "auto",
        "shared",
        "static_pic",
    ],
    visibility = ["PUBLIC"],
)

# N.B. This means static_pic in practice. We do not support non-PIC static
# linking because it is at odds with modern security mitigations like ASLR.
configuration_alias(
    name = "static",
    actual = ":link_style[static_pic]",
)
