# SPDX-FileCopyrightText: 2026 Mercury Technologies, Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

command_alias(
    name = "container",
    args = [
        "--skopeo-exe=$(exe toolchains//:skopeo)",
    ],
    exe = "//snowydeer/container/src/Snowydeer/Container:container_unwrapped",
    # used by //snowydeer:container.bzl
    visibility = ["PUBLIC"],
)
