# SPDX-FileCopyrightText: 2026 Mercury Technologies, Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

load("//haskell:haskell_spec.bzl", "local_packages_spec")

local_packages_spec(
    name = "application_spec",
    srcs = ["ApplicationSpec.hs"],
    main = "Snowydeer.Container.ApplicationSpec",
    deps = [
        "//haskell:aeson",
        "//haskell:base",
        "//haskell:bytestring",
        "//haskell:containers",
        "//haskell:hspec",
        "//haskell:hspec-expectations",
        "//haskell:rio",
        "//haskell:text",
        "//haskell:unliftio",
        "//haskell:unordered-containers",
        "//local-packages/a-mercury-prelude",
        "//snowydeer/container/src/Snowydeer/Container",
        "//snowydeer/container/src/Snowydeer/Container/Metadata",
    ],
)

local_packages_spec(
    name = "container_pipeline_spec",
    srcs = ["PipelineSpec.hs"],
    main = "Snowydeer.Container.PipelineSpec",
    deps = [
        "//haskell:aeson",
        "//haskell:bytestring",
        "//haskell:hspec",
        "//haskell:hspec-expectations",
        "//haskell:rio",
        "//haskell:shakespeare",
        "//haskell:text",
        "//haskell:unliftio",
        "//haskell:unordered-containers",
        "//local-packages/a-mercury-prelude",
        "//snowydeer/container/src/Snowydeer/Container",
    ],
)
