# SPDX-FileCopyrightText: 2026 Mercury Technologies, Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

constraint(
    name = "build_type",
    default = "debug",
    values = [
        "debug",
        "release",
    ],
    visibility = ["PUBLIC"],
)
