-- SPDX-FileCopyrightText: 2026 Mercury Technologies, Inc.
--
-- SPDX-License-Identifier: MIT OR Apache-2.0

module A.MercuryPrelude.ClassyPrelude (module ClassyPrelude) where

import ClassyPrelude hiding
  ( Concurrently,
    Generic,
    -- The 'Handler' type name conflicts with Yesod's 'Handler'.
    Handler,
    and,
    async,
    asyncWithUnmask,
    bracket,
    bracketOnError,
    bracket_,
    catch,
    catches,
    concurrently,
    concurrently_,
    delete,
    deleteBy,
    error,
    finally,
    find,
    fold,
    foldMap,
    foldl',
    foldlM,
    foldr,
    forConcurrently,
    forConcurrently_,
    forM_,
    for_,
    fromEither,
    fromEitherIO,
    fromEitherM,
    getCurrentTime,
    handle,
    -- Hide head and friends to use the Foldable1 ones instead
    head,
    init,
    inits,
    last,
    link,
    linkAsync,
    log,
    mapConcurrently,
    mapConcurrently_,
    mapM_,
    mask,
    mask_,
    maximum,
    maximumBy,
    minimum,
    minimumBy,
    -- Obsolete, replaced with impureNonNull
    nonNull,
    on,
    onException,
    or,
    orElse,
    pooledForConcurrently,
    pooledForConcurrentlyN,
    pooledForConcurrentlyN_,
    pooledForConcurrently_,
    pooledMapConcurrently,
    pooledMapConcurrentlyN,
    pooledMapConcurrentlyN_,
    pooledMapConcurrently_,
    pooledReplicateConcurrently,
    pooledReplicateConcurrentlyN,
    pooledReplicateConcurrentlyN_,
    pooledReplicateConcurrently_,
    product,
    race,
    race_,
    replicateConcurrently,
    replicateConcurrently_,
    runConcurrently,
    sequence_,
    sum,
    tail,
    -- Hide 'throw' so that people use 'throwWithCallStack' instead
    throwIO,
    throwString,
    toList,
    trace,
    traceId,
    traceM,
    traceShow,
    traceShowId,
    traceShowM,
    traverse_,
    try,
    uninterruptibleMask,
    uninterruptibleMask_,
    wait,
    withAsync,
    withAsyncWithUnmask,
    withException,
    -- It seems like consistently people just hide this NonNull stuff from A.MercuryPrelude and use the one from Data.List.NonEmpty
    (<|),
  )
