# SPDX-FileCopyrightText: 2026 Mercury Technologies, Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""
Demo targets for Snowydeer
"""

load("//haskell:mercury_haskell.bzl", "mercury_haskell_binary")
load("//snowydeer:base_image.bzl", "snowydeer_base_image")
load("//snowydeer:container.bzl", "snowydeer_container")
load("//snowydeer:package.bzl", "snowydeer_package")

snowydeer_base_image(
    name = "alpine_base",
    # Run `buck run :alpine_base` to update these.
    digest = "sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40",
    follows_tag = "3.23",
    image_name = "alpine",
    nar_hashes = {
        "aarch64-linux": "sha256-hUcL+KxPzKG8azOlyuRvUPhZUqBXd4I5R6l7bbAnVbU=",
        "x86_64-linux": "sha256-CyZmqg4tEzzp+KlWxuEYIdEXKP1rXyi5Co3KntwGoL8=",
    },
)

snowydeer_container(
    name = "container_with_base",
    base_image = ":alpine_base",
    cmd = [
        "/sbin/apk",
        "--help",
    ],
    description = "Image based on alpine",
    env = {"FOOBAR": "blah"},
    main_contents = [],
)

mercury_haskell_binary(
    name = "hello",
    srcs = ["Hello.hs"],
    main = "Hello",
    deps = [
        "//haskell:base",
    ],
)

snowydeer_package(
    name = "hello_pkg",
    binaries = [
        ":hello",
    ],
)

# This is a wrapper for
# https://nixos.org/manual/nixpkgs/stable/#ssec-pkgs-dockerTools-streamLayeredImage-inputs
snowydeer_container(
    name = "hello_container",
    # No way to do store path references here; need to be put in place as
    # absolute paths using `content`.
    #
    # This command is what will be run inside tini.
    cmd = ["/bin/hello"],

    # contents= in Nix docker tools; will be symlinked into the root of the container.
    # This is a set of paths in addition to `main_contents`.
    contents = [
        # Snowydeer package dependencies
        ":hello_pkg",
        # Nix dependencies are allowed too!
        "toolchains//:ripgrep",
    ],

    # Required. Description of the image.
    description = "Hello world, in a container",

    # Optional. No store paths supported in here either.
    env = {"FOOBAR": "blah"},

    # These fast-changing paths are isolated into their own layers on top of
    # the image. We recommend putting the main application targets in the image
    # into here.
    #
    # Other paths will be intelligently layered into the image.
    main_contents = [
        ":hello_pkg",
        "toolchains//:ripgrep",
    ],

    # Optional. Expose TCP port 2003.
    ports = ["2003/tcp"],
)
